services:
  - type: web
    name: krishibandhu-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: HF_REPO_ID
        value: cosmic1112/Yolo_models
      - key: HF_TOKEN
        sync: false
